### ISSUE TITLE
Unittest fails for pygac>1.3.0

### ISSUE THREAD

**Issue by ninahakansson** [foua-pps/level1c4pps#34]
The unittest fails with version of pygac > 1.3.0. As the cropped GAC file can no longer be read.

Problem will be fixed in for next version of pygac.

The small cropped GAC file was created by cropping the first part of a GAC file:
dd if=NSS.GHRR.TN.D80003.S1147.E1332.B0630506.GC of=NSS.GHRR.TN.D80003.S1147.E1332.B0630506.GC_C bs=10 count=6000

The error message:

```
../home/a001865/opt/CONDA_JUNE/envs/pps2018patch3_level1c4pps/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
Could not load dataset 'DatasetID(name='latitude', wavelength=None, resolution=1050, polarization=None, calibration=None, level=None, modifiers=())': buffer is smaller than requested size
Traceback (most recent call last):
  File "/home/a001865/opt/CONDA_JUNE/envs/pps2018patch3_level1c4pps/lib/python3.6/site-packages/satpy/readers/yaml_reader.py", line 782, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/a001865/opt/CONDA_JUNE/envs/pps2018patch3_level1c4pps/lib/python3.6/site-packages/satpy/readers/yaml_reader.py", line 667, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/a001865/opt/CONDA_JUNE/envs/pps2018patch3_level1c4pps/lib/python3.6/site-packages/satpy/readers/yaml_reader.py", line 643, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/a001865/opt/CONDA_JUNE/envs/pps2018patch3_level1c4pps/lib/python3.6/site-packages/satpy/readers/avhrr_l1b_gaclac.py", line 126, in get_dataset
    self.reader.read(self.filename)
  File "/home/a001865/opt/CONDA_JUNE/envs/pps2018patch3_level1c4pps/lib/python3.6/site-packages/pygac/pod_reader.py", line 257, in read
    count=self.head["number_of_scans"])
ValueError: buffer is smaller than requested size
```

**Comment by ninahakansson** [comment]
Solved with latest version of pygac (1.4.0).
