### ISSUE TITLE
sqlite import issue while running metimage2pps.py

### ISSUE THREAD

**Issue by CptOrange16** [foua-pps/level1c4pps#89]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python

python3 metimage2pps.py -pps_ch -o ./mydata W_XX-EUMETSAT-Darmstadt,SAT,SGA1-VII-1B-RAD_C_EUMT_20210507110759_G_D_20080223100003_20080223100103_T_B____.nc

```
#### Problem description

I believe there is something missing with my installation that is causing this issue, maybe some library.

#### Expected Output

Program executes and generates files in given directory.

#### Actual Result

```python
Traceback (most recent call last):
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 551, in find_python_name
    __import__(module_name)
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/modifiers/__init__.py", line 23, in <module>
    from .atmosphere import CO2Corrector  # noqa: F401, I001
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/modifiers/atmosphere.py", line 27, in <module>
    from satpy.modifiers._crefl import ReflectanceCorrector  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/modifiers/_crefl.py", line 27, in <module>
    from satpy.modifiers.angles import get_angles
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/modifiers/angles.py", line 36, in <module>
    from pyorbital.orbital import get_observer_look
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/pyorbital/orbital.py", line 34, in <module>
    from pyorbital import astronomy, dt2np, tlefile
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/pyorbital/tlefile.py", line 36, in <module>
    import sqlite3
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/lib-dynload/_sqlite3.cpython-312-x86_64-linux-gnu.so: undefined symbol: sqlite3_deserialize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sara/anaconda3/envs/ppsEPSSG/bin/metimage2pps.py", line 53, in <module>
    process_one_scene(options.files, options.out_dir,
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/level1c4pps/metimage2pps_lib.py", line 148, in process_one_scene
    scn_.load(MY_BANDNAMES + ANGLE_NAMES + ['lat_pixels', 'lon_pixels'])
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/scene.py", line 1449, in load
    self._update_dependency_tree(needed_datasets, query)
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/scene.py", line 1459, in _update_dependency_tree
    comps, mods = load_compositor_configs_for_sensors(self.sensor_names)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/composites/config_loader.py", line 305, in load_compositor_configs_for_sensors
    sensor_comps, sensor_mods = load_compositor_configs_for_sensor(sensor_name)[:2]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/composites/config_loader.py", line 235, in _add_config_path_wrapper
    return _call_without_config_path_wrapper(sensor_name, config_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/composites/config_loader.py", line 229, in _call_without_config_path_wrapper
    return func(sensor_name)
           ^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/composites/config_loader.py", line 281, in load_compositor_configs_for_sensor
    return _load_config(composite_configs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/composites/config_loader.py", line 183, in _load_config
    conf = recursive_dict_update(conf, yaml.load(conf_file, Loader=UnsafeLoader))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 102, in construct_object
    data = constructor(self, tag_suffix, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 570, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 719, in find_python_name
    return super(UnsafeConstructor, self).find_python_name(name, mark, unsafe=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/yaml/constructor.py", line 553, in find_python_name
    raise ConstructorError("while constructing a Python object", mark,
yaml.constructor.ConstructorError: while constructing a Python object
cannot find module 'satpy.modifiers' (/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/lib-dynload/_sqlite3.cpython-312-x86_64-linux-gnu.so: undefined symbol: sqlite3_deserialize)
  in "/home/sara/anaconda3/envs/ppsEPSSG/lib/python3.12/site-packages/satpy/etc/composites/vii.yaml", line 4, column 15

```

#### Versions of Python, package at hand and relevant dependencies

I am running the script using a conda environment with the following packages and versions:
``` yaml
# packages in environment at /home/sara/anaconda3/envs/ppsEPSSG2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.1.0              pyhd8ed1ab_0    conda-forge
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.12               h4ab18f5_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.22              hbd3ac97_10    conda-forge
aws-c-cal                 0.7.1                h87b94db_1    conda-forge
aws-c-common              0.9.23               h4ab18f5_0    conda-forge
aws-c-compression         0.2.18               he027950_7    conda-forge
aws-c-event-stream        0.4.2               h7671281_15    conda-forge
aws-c-http                0.8.2                he17ee6b_6    conda-forge
aws-c-io                  0.14.10              h826b7d6_1    conda-forge
aws-c-mqtt                0.10.4               hcd6a914_8    conda-forge
aws-c-s3                  0.6.0                h365ddd8_2    conda-forge
aws-c-sdkutils            0.1.16               he027950_3    conda-forge
aws-checksums             0.1.18               he027950_7    conda-forge
aws-crt-cpp               0.27.3               hda66527_2    conda-forge
aws-sdk-cpp               1.11.329             h46c3b66_9    conda-forge
azure-core-cpp            1.12.0               h830ed8b_0    conda-forge
azure-identity-cpp        1.8.0                hdb0d106_1    conda-forge
azure-storage-blobs-cpp   12.11.0              ha67cba7_1    conda-forge
azure-storage-common-cpp  12.6.0               he3f277c_1    conda-forge
azure-storage-files-datalake-cpp 12.10.0              h29b5301_1    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
bokeh                     3.5.0              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py312h30efb56_1    conda-forge
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.32.2               h4bc722e_0    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.0               hbb29018_2    conda-forge
cartopy                   0.23.0          py312h1d6d2e6_1    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312hf06ca03_0    conda-forge
cfitsio                   4.4.1                hf8ad068_0    conda-forge
cftime                    1.6.4           py312h085067d_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
configobj                 5.0.8              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h8572e83_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.3          py312h98912ed_0    conda-forge
dask                      2024.7.0           pyhd8ed1ab_0    conda-forge
dask-core                 2024.7.0           pyhd8ed1ab_0    conda-forge
dask-expr                 1.1.7              pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
distributed               2024.7.0           pyhd8ed1ab_0    conda-forge
donfig                    0.8.1.post1        pyhd8ed1ab_0    conda-forge
eccodes                   2.33.0               he84ddb8_0    conda-forge
expat                     2.6.2                h6a678d5_0  
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
flatbuffers               24.3.25              h59595ed_0    conda-forge
fmt                       10.2.1               h00ab1b0_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1          py312h41a817b_0    conda-forge
freeglut                  3.2.2                ha6d2627_3    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freexl                    2.0.0                h743c826_0    conda-forge
fsspec                    2024.6.1           pyhff2d567_0    conda-forge
gast                      0.5.5              pyhd8ed1ab_0    conda-forge
geos                      3.12.2               hac33072_0    conda-forge
geotiff                   1.7.3                hf7fa9e8_1    conda-forge
gettext                   0.22.5               h59595ed_2    conda-forge
gettext-tools             0.22.5               h59595ed_2    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
glib                      2.80.3               h8a4344b_1    conda-forge
glib-tools                2.80.3               h73ef956_1    conda-forge
glog                      0.7.1                hbabe93e_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
grpcio                    1.62.2          py312hb06c811_0    conda-forge
gst-plugins-base          1.24.5               hbaaba92_0    conda-forge
gstreamer                 1.24.5               haf2f30d_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5netcdf                  1.3.0              pyhd8ed1ab_0    conda-forge
h5py                      3.11.0          nompi_py312hb7ab980_102    conda-forge
harfbuzz                  9.0.0                hfac3d4d_0    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        8.0.0              pyha770c72_0    conda-forge
importlib_metadata        8.0.0                hd8ed1ab_0    conda-forge
jasper                    4.2.4                h536e39c_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
json-c                    0.17                 h1220068_1    conda-forge
kealib                    1.5.3                hee9dde6_1    conda-forge
keras                     3.4.1              pyhd8ed1ab_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py312h8572e83_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      4.0.0                h27087fc_0    conda-forge
level1c4pps               0.2.33                     py_0    file:///home/sara/workspace/IPMA/safnwc_pps_epssg/pps_EPSSG_SAFbeta6_conda_packages
libabseil                 20240116.2      cxx17_he02047a_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libarrow                  16.1.0          h34456a7_14_cpu    conda-forge
libarrow-acero            16.1.0          he02047a_14_cpu    conda-forge
libarrow-dataset          16.1.0          he02047a_14_cpu    conda-forge
libarrow-substrait        16.1.0          hc9a23c6_14_cpu    conda-forge
libasprintf               0.22.5               h661eb56_2    conda-forge
libasprintf-devel         0.22.5               h661eb56_2    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libclang-cpp15            15.0.7          default_h127d8a8_5    conda-forge
libclang13                18.1.8          default_h6ae225f_0    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.8.0                hca28451_1    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.4                h6a678d5_1  
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgcrypt                 1.11.0               h4ab18f5_0    conda-forge
libgdal                   3.9.1                ha770c72_7    conda-forge
libgdal-core              3.9.1                h1d1841c_7    conda-forge
libgdal-fits              3.9.1                hdd6600c_7    conda-forge
libgdal-grib              3.9.1                h5f34788_7    conda-forge
libgdal-hdf4              3.9.1                ha39a594_7    conda-forge
libgdal-hdf5              3.9.1                ha2ed5f0_7    conda-forge
libgdal-jp2openjpeg       3.9.1                h2ebfdf0_7    conda-forge
libgdal-kea               3.9.1                h2b45729_7    conda-forge
libgdal-netcdf            3.9.1                h94e7027_7    conda-forge
libgdal-pdf               3.9.1                h562c687_7    conda-forge
libgdal-pg                3.9.1                he047751_7    conda-forge
libgdal-postgisraster     3.9.1                he047751_7    conda-forge
libgdal-tiledb            3.9.1                hfcb00c0_7    conda-forge
libgdal-xls               3.9.1                h062f1c4_7    conda-forge
libgettextpo              0.22.5               h59595ed_2    conda-forge
libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libglib                   2.80.3               h8a4344b_1    conda-forge
libglu                    9.0.0             ha6d2627_1004    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libgoogle-cloud           2.26.0               h26d7fe4_0    conda-forge
libgoogle-cloud-storage   2.26.0               ha262f82_0    conda-forge
libgpg-error              1.50                 h4f305b6_0    conda-forge
libgrpc                   1.62.2               h15f2491_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
libkml                    1.3.0             hbbc8833_1020    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libllvm18                 18.1.8               h8b73ec9_1    conda-forge
libnetcdf                 4.9.2           nompi_h135f659_114    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.5                h4ab18f5_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libparquet                16.1.0          h9e5060d_14_cpu    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     16.3                 ha72fbe1_0    conda-forge
libprotobuf               4.25.3               h08a7969_0    conda-forge
libre2-11                 2023.09.01           h5a48ba9_2    conda-forge
librttopo                 1.1.0               hc670b87_16    conda-forge
libsndfile                1.2.2                hc60ed4a_1    conda-forge
libspatialite             5.1.0                h15fa968_8    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libsystemd0               255                  h3516f8a_1    conda-forge
libthrift                 0.19.0               hb90f79a_1    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hd590300_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h2c5496b_1    conda-forge
libxml2                   2.12.7               h4c95cb1_3    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.3           py312h03f37cb_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py312h98912ed_0    conda-forge
matplotlib                3.9.1           py312h7900ff3_0    conda-forge
matplotlib-base           3.9.1           py312h9201f00_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
minizip                   4.0.7                h401b404_0    conda-forge
ml_dtypes                 0.3.2           py312hfb8ada1_0    conda-forge
mpg123                    1.32.6               h59595ed_0    conda-forge
msgpack-python            1.0.8           py312h2492b07_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.3.0                hf1915f5_4    conda-forge
mysql-libs                8.3.0                hca2cd23_4    conda-forge
namex                     0.0.8              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h6a678d5_0  
netcdf4                   1.7.1           nompi_py312h1ef7fb6_101    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.102                h593d115_0    conda-forge
numcodecs                 0.12.1          py312h7070661_1    conda-forge
numexpr                   2.10.0          py312hf412c99_100    conda-forge
numpy                     1.26.4          py312heda63a1_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
opt_einsum                3.3.0              pyhc1e730c_2    conda-forge
optree                    0.12.1          py312h3402730_0    conda-forge
orc                       2.0.1                h17fec99_1    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py312h1d6d2e6_1    conda-forge
partd                     1.4.2              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h0f59acf_0    conda-forge
pillow                    10.4.0          py312h287a98d_0    conda-forge
pip                       24.0            py312h06a4308_0  
pixman                    0.43.2               h59595ed_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
pooch                     1.8.2              pyhd8ed1ab_0    conda-forge
poppler                   24.07.0              hb0d391f_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.3                 h8e811e2_0    conda-forge
proj                      9.4.1                hb784bbd_0    conda-forge
protobuf                  4.25.3          py312h72fbbdf_0    conda-forge
psutil                    6.0.0           py312h9a8786e_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulseaudio-client         17.0                 hb77b528_0    conda-forge
pyarrow                   16.1.0          py312h9cebb41_4    conda-forge
pyarrow-core              16.1.0          py312h70856f0_4_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pygrib                    2.1.6           py312h5b226fc_0    conda-forge
pyhdf                     0.11.4          py312heb8d80e_1    conda-forge
pykdtree                  1.3.12          py312h085067d_1    conda-forge
pyorbital                 1.8.3              pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.1           py312h5d05ceb_7    conda-forge
pyqt                      5.15.9          py312h949fe66_5    conda-forge
pyqt5-sip                 12.12.2         py312h30efb56_5    conda-forge
pyresample                1.28.4          py312h1df14c2_0    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pyspectral                0.13.3             pyhd8ed1ab_0    conda-forge
python                    3.12.2          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-flatbuffers        24.3.25            pyh59ac667_0    conda-forge
python-geotiepoints       1.7.4           py312h085067d_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py312h98912ed_1    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
qt-main                   5.15.8              h320f8da_24    conda-forge
rasterio                  1.3.10          py312hc022a17_4    conda-forge
re2                       2023.09.01           h7f4b329_2    conda-forge
readline                  8.2                  h5eee18b_0  
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
s2n                       1.4.17               he19d79f_0    conda-forge
satpy                     0.49.0             pyhd8ed1ab_0    conda-forge
scikit-learn              1.5.1           py312h775a589_0    conda-forge
scipy                     1.14.0          py312hc2bc53b_1    conda-forge
setuptools                69.5.1          py312h06a4308_0  
shapely                   2.0.5           py312h8413631_0    conda-forge
sip                       6.7.12          py312h30efb56_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
spdlog                    1.13.0               hd2e6256_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
tensorboard               2.16.2             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0           py312h241aef2_1    conda-forge
tensorflow                2.16.2          cpu_py312h69ecde4_0    conda-forge
tensorflow-base           2.16.2          cpu_py312h5c1443c_0    conda-forge
tensorflow-estimator      2.16.2          cpu_py312hbf2973a_0    conda-forge
termcolor                 2.4.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tiledb                    2.24.2               hc55ee95_2    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py312h9a8786e_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
trollimage                1.24.0          py312h1d6d2e6_0    conda-forge
trollsift                 0.5.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzcode                    2024a                h3f72095_0    conda-forge
tzdata                    2024a                h04d1e81_0  
uriparser                 0.9.8                hac33072_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
werkzeug                  3.0.3              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0          py312h06a4308_0  
wrapt                     1.16.0          py312h98912ed_0    conda-forge
xarray                    2024.6.0           pyhd8ed1ab_1    conda-forge
xcb-util                  0.4.1                hb711507_2    conda-forge
xcb-util-image            0.4.0                hb711507_2    conda-forge
xcb-util-keysyms          0.4.1                hb711507_0    conda-forge
xcb-util-renderutil       0.3.10               hb711507_0    conda-forge
xcb-util-wm               0.4.2                hb711507_0    conda-forge
xerces-c                  3.2.5                hac6953d_0    conda-forge
xkeyboard-config          2.42                 h4ab18f5_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xyzservices               2024.6.0           pyhd8ed1ab_0    conda-forge
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7f98852_2    conda-forge
zarr                      2.18.2             pyhd8ed1ab_0    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h4ab18f5_1    conda-forge
zstandard                 0.23.0          py312h3483029_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

```

Is there any library incompatibility that i should be aware?
Thanks

**Comment by CptOrange16** [comment]
I forced the reinstallation of sqlite and libsqlite in my conda environment and it is now working.
New versions are:
ncurses                   6.5 
sqlite                    3.46.0
